patreon: jenniferdonaruwu
custom: ['https://lovebott.herokuapp.com', 'https://github.com/AahhsSjsj/Bot-Tutoriales-V13', 'https://dsc.gg/ts-community', 'https://discord.gg/Q9drrstchp', 'https://github.com/Lovebott/Bot-Discord-V13']
